parameter_defaults:
  config_data:
    deploy_count:
      gold_server_count: 1
      silver_server_count: 1
      bronze_server_count: 1

    gold_flavor: g1.2xlarge
    silver_flavor: s1.2xlarge
    bronze_flavor: b1.2xlarge
    
    boot_volume_size: 40
    boot_volume_type: "stripe-vdo"
   
    heat_node: 'https://raw.githubusercontent.com/gprocunier/dcib/main/openstack/benchmark/nested/node.yaml'
    ssh_keypair: 'bench-key'
    # os_image: 'CentOS-Stream-GenericCloud-8-20210603.0.x86_64'
    os_image: a2111044-2ca0-467a-b45c-b93158c72f6f
    # workload_network: greg-default
    workload_network: 7d5c26b4-9419-4a66-acf0-7723c28a27e7
    workload_subnets:
      - subnet_id: 5a2e5dbe-9d58-4b46-bdc4-232f7d2ee108
    # workload_sg: Default
    workload_sg:
      - 92b3df14-2e18-49c9-8aa9-d6df89d319cf
      
    # define params for creating a share in manila for collecting telemetry
    file_share_size_gb: 32
    file_share_acl:
      - access_level: "rw"
        access_type: "ip"
        access_to: "192.168.1.0/24"
