heat_template_version: rocky

description: >
  Stand up a number of instances in different priority bands to test oversubscription
  policies.  Among other things...

parameters:
  config_data:
    type: json
    default: {}

resources:

# Stand up file shares
  shares:
     type: OS::Heat::Stack 
     properties:
       template: { get_file: 'https://raw.githubusercontent.com/gprocunier/dcib/main/openstack/benchmark/nested/file-shares.yaml' }
       parameters:

# Stand up instances
  servers:
     type: OS::Heat::Stack 
     properties:
       template: { get_file: 'https://raw.githubusercontent.com/gprocunier/dcib/main/openstack/benchmark/nested/servers.yaml' }
       parameters:
        stack_bridge:
          share_location:
            get_attr: [ shares, outputs, export_location ]
           
outputs:
