dcib:
  hosts:
    localhost:
  vars:
    unit: "GiB"

    raidcfg:
      "/dev/md0":
        members: 8
        chunk: 512 # KiB
        devices:
          - /dev/disk/by-id/nvme-eui.002538b11150b8c8-part1
          - /dev/disk/by-id/nvme-eui.002538b21150aa92-part1
          - /dev/disk/by-id/nvme-eui.002538b11150b8c9-part1
          - /dev/disk/by-id/nvme-eui.002538b2115098b3-part1
          - /dev/disk/by-id/nvme-eui.002538b11150c7b6-part1
          - /dev/disk/by-id/nvme-eui.002538b211508b77-part1
          - /dev/disk/by-id/nvme-eui.002538b11150b7c8-part1
          - /dev/disk/by-id/nvme-eui.002538b211508b79-part1
      "/dev/md1":
        members: 8
        chunk: 512
        devices:
          - /dev/disk/by-id/nvme-eui.002538b11150b8c8-part2
          - /dev/disk/by-id/nvme-eui.002538b21150aa92-part2
          - /dev/disk/by-id/nvme-eui.002538b11150b8c9-part2
          - /dev/disk/by-id/nvme-eui.002538b2115098b3-part2
          - /dev/disk/by-id/nvme-eui.002538b11150c7b6-part2
          - /dev/disk/by-id/nvme-eui.002538b211508b77-part2
          - /dev/disk/by-id/nvme-eui.002538b11150b7c8-part2
          - /dev/disk/by-id/nvme-eui.002538b211508b79-part2
      "/dev/md2":
        members: 4
        chunk: 512
        devices:
          - /dev/disk/by-id/nvme-eui.343336304e9172650025384100000003-part1
          - /dev/disk/by-id/nvme-eui.343336304e9166570025384100000003-part1
          - /dev/disk/by-id/nvme-eui.343336304d8223120025384100000004-part1
          - /dev/disk/by-id/nvme-eui.343336304d8223100025384100000004-part1
      "/dev/md3":
        members: 2
        chunk: 512
        devices:
          - /dev/disk/by-id/nvme-eui.01000000000000005cd2e41f893b5351-part1
          - /dev/disk/by-id/nvme-eui.01000000000000005cd2e49227155351-part1

    # 10:1 for VMs or containers, 3:1 for Objects
    vdocfg:
      "samsung_980p_vdo":
        device: "/dev/md0"
        logical_size: 20t
        compression: enabled
        deduplication: enabled
        vdoLogicalThreads: 8
        vdoPhysicalThreads: 6
        vcoCpuThreads: 6
        vdoHashZoneThreads: 3
        vdoAckThreads: 6
        vdoBioThreads: 8
        vdoSlabSize: 32g

    lvmcfg:
      "samsung_983e_4x_r0":
        device: /dev/md2
        pe_size: "32"
        vg_options: "--alloc contiguous"
      "samsung_983e_00":
        device: /dev/disk/by-id/nvme-eui.343336304e9172650025384100000003-part2
        pe_size: "32"
        vg_options: "--alloc contiguous"
      "samsung_983e_01":
        device: /dev/disk/by-id/nvme-eui.343336304e9166570025384100000003-part2
        pe_size: "32"
        vg_options: "--alloc contiguous"
      "samsung_983e_02":
        device: /dev/disk/by-id/nvme-eui.343336304d8223120025384100000004-part2
        pe_size: "32"
        vg_options: "--alloc contiguous"
      "samsung_983e_03":
        device: /dev/disk/by-id/nvme-eui.343336304d8223100025384100000004-part2
        pe_size: "32"
        vg_options: "--alloc contiguous"
      "intel_p5800x_2x_r0":
        device: /dev/md3
        pe_size: "32"
        vg_options: "--alloc contiguous"
      "intel_p5800x_00":
        device: /dev/disk/by-id/nvme-eui.01000000000000005cd2e41f893b5351-part2
        pe_size: "32"
        vg_options: "--alloc contiguous"
      "intel_p5800x_01":
        device: /dev/disk/by-id/nvme-eui.01000000000000005cd2e49227155351-part2
        pe_size: "32"
        vg_options: "--alloc contiguous"
        
    devs:
      samsung_980p_1tb:
        - path: /dev/disk/by-id/nvme-eui.002538b11150b8c8
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
        - path: /dev/disk/by-id/nvme-eui.002538b21150aa92
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
        - path: /dev/disk/by-id/nvme-eui.002538b11150b8c9
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
        - path: /dev/disk/by-id/nvme-eui.002538b2115098b3
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
        - path: /dev/disk/by-id/nvme-eui.002538b11150c7b6
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
        - path: /dev/disk/by-id/nvme-eui.002538b211508b77
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
        - path: /dev/disk/by-id/nvme-eui.002538b11150b7c8
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
        - path: /dev/disk/by-id/nvme-eui.002538b211508b79
          table:
            - size: 512GiB
              raid: /dev/md0
            - size: remain
              raid: /dev/md1
      samsung_983e_2tb:
        - path: /dev/disk/by-id/nvme-eui.343336304e9172650025384100000003
          table:
            - size: 1024GiB
              raid: /dev/md2
            - size: remain
              raid: none
        - path: /dev/disk/by-id/nvme-eui.343336304e9166570025384100000003
          table:
            - size: 1024GiB
              raid: /dev/md2
            - size: remain
              raid: none
        - path: /dev/disk/by-id/nvme-eui.343336304d8223120025384100000004
          table:
            - size: 1024GiB
              raid: /dev/md2
            - size: remain
              raid: none
        - path: /dev/disk/by-id/nvme-eui.343336304d8223100025384100000004
          table:
            - size: 1024GiB
              raid: /dev/md2
            - size: remain
              raid: none
      intel_optane_p5800x:
        - path: /dev/disk/by-id/nvme-eui.01000000000000005cd2e41f893b5351
          table:
            - size: 256GiB
              raid: /dev/md3
            - size: remain
              raid: none 
        - path: /dev/disk/by-id/nvme-eui.01000000000000005cd2e49227155351
          table:
            - size: 256GiB
              raid: /dev/md3
            - size: remain
              raid: none 
