apiVersion: v1
#  domain our DNS is authoritative for
baseDomain: ipa.example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    openstack:
      rootVolume:
        # cinder volume type
        # we put the os of the compute on the vdo backend since we are
        # going to install cinder and ceph storage classes for workloads
        type: 'stripe-vdo'
        # gigabytes
        size: 40
      # 8 vcpu 16gb bronze tier 204 share class
      type: b1.2xlarge
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: control
  platform:
    openstack:
      rootVolume:
        # the control plane is busy and runs etc which is an io pig
        type: 'stripe-performance'
        size: 40
      # 4 vcpu 16gb bronze tier
      type: b1.xlarge
  replicas: 3
metadata:
  creationTimestamp: null
  name: dcib
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  # created by the installer, host networking for the nodes
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: Kuryr
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    apiFloatingIP: 192.168.1.80
    # generated by make manifests
    apiVIP: 10.0.0.5
    # openstack project/tenant for the deployment
    cloud: openshift
    # incase a previously mentioned flavor is not available
    defaultMachinePlatform:
      type: b1.xlarge
    # dns is critical to getting openshift deployed, this is the one im hosting
    # ipa.example.com on
    externalDNS:
      - 192.168.1.14
    # name of the external network where the floating ips live
    externalNetwork: external
    ingressVIP: 10.0.0.7
    trunkSupport: true
    octaviaSupport: true
    # rhcos gets uploaded to glance and these are performance and behavioral 
    # properties we need to set
    clusterOSImageProperties:
      "hw_disk_bus": "scsi"
      "hw_rng_model": "virtio"
      "hw_scsi_model": "virtio-scsi"
      "hw_vif_model": "virtio"
      "hw_vif_multiqueue_enabled": "true"
      "hw_watchdog_action": "reset"
      "hw_qemu_guest_agent": "yes"
      "os_distro": "rhel8.4"
      "os_type": "linux"
      "os_require_quiesce": "yes"
      "cinder_img_volume_type": "stripe-performance"
      
publish: External
pullSecret: LotsOfSuperSecretPullSecretStuff
sshKey: NotTerriblySecretSshPublicKeyStuff
