heat_template_version: rocky

description: attach volumes to instances

parameters:
  volume_size:
    type: number
    default: 1
    constraints:
      - range: { min: 1, max: 1024 }
  instance_id:
    type: string
  volume_type:
    type: string
  volume_description:
    type: string
    
resources:

  volume:
    type: OS::Cinder::Volume
    properties:
      size:
        get_param: volume_size
      description:
        get_param: volume_description
      volume_type:
        get_param: voltype

  attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id:
        get_resource: volume
      instance_uuid:
        get_param: instance_id
