heat_template_version: rocky

description: attach volumes to instances

parameters:
  extra_bridge:
    type: json
    default: {}
    
resources:

  volume:
    type: OS::Cinder::Volume
    properties:
      size:
        get_param: [ extra_bridge, volume_size ]
     #description:
     #   list_join: ['', [ {get_param: [ extra_bridge, volume_description ] }, ' data volume']]
      volume_type:
        get_param: [ extra_bridge, volume_type ]

  attachment:
    type: OS::Cinder::VolumeAttachment
    depends_on: volume
    properties:
      volume_id:
        get_resource: volume
      instance_uuid:
        get_param: [ extra_bridge, instance_id ]
