heat_template_version: rocky

description: attach volumes to instances

parameters:
  extra_volumes:
    type: json
    default: {}
  instance_id:
    type: string
    default: 'id_nope'
  volume_description:
    type: string
    default: 'desc_nope'
  index:
    type: number

resources:

  volume:
    type: OS::Cinder::Volume
    properties:
      size:
        get_param: [ extra_volumes, { get_param: index }, size ]
      description:
        list_join: [' ', [ { get_param: volume_description }, 'data volume']]
      volume_type:
        get_param: [ extra_volumes, { get_param: index }, volume_type ]

  attachment:
    type: OS::Cinder::VolumeAttachment
    depends_on: volume
    properties:
      volume_id:
        get_resource: volume
      instance_uuid:
        get_param: instance_id
        
  wait:
    type: OS::Heat::WaitCondition
    depends_on: attachment
    properties:
      count: 1
      handle: { get_resource: wait_handle }
      timeout: 600
      
  wait_handle:
    type: OS::Heat::WaitConditionHandle
    depends_on: attachment
