heat_template_version: rocky
description: >
  Create NFS file share for instances to write telemetry to.
  
parameters:
  config_data:
    type: json
    default: {}

resources:

  share:
    type: OS::Manila::Share
    properties:
      name: "telemetry"
      description: "benchmark telemetry collection share"
      is_public: true
      share_protocol: "NFS"
      size:
        get_param: [ config_data, file_share_size_gb ]
      access_rules:
        get_param: [ config_data, file_share_acl ]
        
outputs:
  export_location:
    value:
      get_attr: [ share, show, export_locations ]
  status:
    value:
      get_attr: [ share, show, status ]
  details:
    value:
      get_attr: [ share, show, show ]
