heat_template_version: rocky
  
parameters:
  config_data:
    type: json
    default: {}
  node_bridge:
    type: json
    default: {}

resources:

  my_instance_port:
    type: OS::Neutron::Port
    properties:
      network_id:
        get_param: [ node_bridge, private_net_id  ]
      fixed_ips:
        get_param: [ node_bridge, fixed_ips ]
#     security_groups:
#       get_param: [ node_bridge, security_groups ]

  nodeconfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      inputs:
      outputs:
        - name: deployment-output
      config:
        get_param: [ node_bridge, cloud_init ]

  mimepayload:
    type: OS::Heat::MultipartMime
    depends_on: nodeconfig
    properties:
      parts:
        - config:
            get_resource: nodeconfig

