heat_template_version: rocky
  
parameters:
  config_data:
    type: json
    default: {}
  stack_bridge:
    type: json
    default: {}
  node_bridge:
    type: json
    default: {}

resources:

  gold_server_rg:
    type: OS::Heat::ResourceGroup
    properties:
      count:
        get_param: [ config_data, deploy_count, gold_server_count ]
      resource_def:
        type:
          get_param: [ config_data, templates, node ]
        properties:
          node_bridge:
            NodeIndex: "%index%"
            guest_name: "gold-workload-%index%"
            key_name:
              get_param: [ config_data, ssh_keypair ]
            boot_volume_size:
              get_param: [ config_data, boot_volume_size ]
            boot_volume_type:
              get_param: [ config_data, boot_volume_type ]
            image:
              get_param: [ config_data, os_image ]
            extra_volumes:
              get_param: [ config_data, gold ]
            flavor:
              get_param: [ config_data, gold_flavor ]
            fixed_ips:
              get_param: [ config_data, workload_subnets ]
            private_net_id:
              get_param: [ config_data, workload_network ]
            security_groups:
              get_param: [ config_data, workload_sg ]
            share_location:
              get_param: [ stack_bridge, share_location ]
            cloud_init:
              get_file: https://raw.githubusercontent.com/gprocunier/dcib/main/openstack/benchmark/cloud-init/node-config-centos.sh

  silver_server_rg:
    type: OS::Heat::ResourceGroup
    properties:
      count:
        get_param: [ config_data, deploy_count, silver_server_count ]
      resource_def:
        type:
          get_param: [ config_data, heat_node ]
        properties:
          node_bridge:
            NodeIndex: "%index%"
            guest_name: "silver-workload-%index%"
            key_name:
              get_param: [ config_data, ssh_keypair ]
            boot_volume_size:
              get_param: [ config_data, boot_volume_size ]
            boot_volume_type:
              get_param: [ config_data, boot_volume_type ]
            image:
              get_param: [ config_data, os_image ]
            extra_volumes:
              get_param: [ config_data, silver ]
            flavor:
              get_param: [ config_data, silver_flavor ]
            fixed_ips:
              get_param: [ config_data, workload_subnets ]
            private_net_id:
              get_param: [ config_data, workload_network ]
            security_groups:
              get_param: [ config_data, workload_sg ]
            share_info:
              get_param: [ stack_bridge, share_location ]
            cloud_init:
              get_file: https://raw.githubusercontent.com/gprocunier/dcib/main/openstack/benchmark/cloud-init/node-config-centos.sh

  bronze_server_rg:
    type: OS::Heat::ResourceGroup
    properties:
      count:
        get_param: [ config_data, deploy_count, bronze_server_count ]
      resource_def:
        type:
          get_param: [ config_data, heat_node ]
        properties:
          node_bridge:
            NodeIndex: "%index%"
            guest_name: "bronze-workload-%index%"
            key_name:
              get_param: [ config_data, ssh_keypair ]
            boot_volume_size:
              get_param: [ config_data, boot_volume_size ]
            boot_volume_type:
              get_param: [ config_data, boot_volume_type ]
            image:
              get_param: [ config_data, os_image ]
            extra_volumes:
              get_param: [ config_data, bronze ]
            flavor:
              get_param: [ config_data, bronze_flavor ]
            fixed_ips:
              get_param: [ config_data, workload_subnets ]
            private_net_id:
              get_param: [ config_data, workload_network ]
            security_groups:
              get_param: [ config_data, workload_sg ]
            share_info:
              get_param: [ stack_bridge, share_location ]
            cloud_init:
              get_file: https://raw.githubusercontent.com/gprocunier/dcib/main/openstack/benchmark/cloud-init/node-config-centos.sh
